### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by lqzhgood** [mantou132/Spotify-Lyrics#10]
add transparent background options ?

like this 
https://www.appinn.com/mcool-music-player/
![image](https://user-images.githubusercontent.com/9134671/75447233-ed0fd300-59a3-11ea-9a7e-988ba279c262.png)

**Comment by mantou132** [comment]
https://w3c.github.io/picture-in-picture/

应该没办法做到透明背景。

**Comment by lqzhgood** [comment]
研究了一下 有几个问题请教一下~

PIP 就是一个(且只能是) <code>video</code>, 
pip不受css 控制
video默认背景 黑色，填入 透明canvas 也只能显示黑色。

==> 所以做不了 **透明**。

**Comment by lqzhgood** [comment]
不死心 早上起来试了下~~
哎 果然默认背景是黑的。。。

把着色代码
https://github.com/mantou132/Spotify-Lyrics/blob/594b1803bd1e3760fef2c48a58e115b296db1ecc/src/page/index.ts#L63

修改为 半透明红色
```javascript
      ctx.fillStyle= "rgba(255 ,0 ,255,0.5)";
      ctx.fillRect(  0, 0, WIDTH, HEIGHT);
```

结果是 黑色叠底 + 半透明红色~~ 
说明背景是 纯黑的。

![image](https://user-images.githubusercontent.com/9134671/75599793-492d4100-5ae3-11ea-9852-2647e9e7a0c3.png)

**Comment by mantou132** [comment]
不能透明挺正常的，窗口是系统创建的，不是js，css。就算背景透明了窗口阴影还去不掉呢
