### ISSUE TITLE
Error: Failed to fetch

### ISSUE THREAD

**Issue by oRevived** [mantou132/Spotify-Lyrics#100]
When opening the lyrics on YouTube Music or Spotify it will display an error message that says "Error: Failed to fetch". I suspect this is because the[ Google Cloud Function server that Spotify Lyrics uses](https://us-central1-spotify-lyrics-ef482.cloudfunctions.net/) is not working (it says "Error: Forbidden. Your client does not have permission to get URL / from this server." if you try to access it. I'm guessing that this is not normal).

Additionally, if you try to visit https://us-central1-spotify-lyrics-ef482.cloudfunctions.net/getLyric it will say that the server has encountered an error and could not complete the request.

Thanks for reading.

**Comment by mantou132** [comment]
my bad, reply too late

I had some problems with my Google Cloud account, so Cloud Functions were disabled, just now I fixed him

**Comment by oRevived** [comment]
Thank you so much! :)
