### ISSUE TITLE
Lyrics button in YouTube Music is gone

### ISSUE THREAD

**Issue by oRevived** [mantou132/Spotify-Lyrics#101]
The lyrics button in YouTube Music has disappeared, but you can still press the L key to bring up the lyrics. However, you are no longer able to open the LRC editor because you cannot middle click the lyrics button as it's no longer there. 

I'm guessing there has been some changes to the code in YouTube Music as the button is still present in Spotify.

Thanks for reading :)

**Comment by mantou132** [comment]
Your guess is correct, I just fixed it in v1.5.30.

It seems that YouTube will make a big update in the near future, and I will continue to modify the lyrics button at that time

**Comment by oRevived** [comment]
Thank you! This extension is great :)
