### ISSUE TITLE
错误：

### ISSUE THREAD

**Issue by XYSC** [mantou132/Spotify-Lyrics#107]
您好，您的插件很好用，今天突然不能显示歌词了，显示“错误：”，不知道什么原因呢
ps：找了好多其他插件都不好用，您的插件在我看来最好用了...可以的话，期待修复~

![image](https://github.com/mantou132/Spotify-Lyrics/assets/52696129/5899f3f0-0c82-4bd0-89ef-3329fed4843b)

**Comment by over-space** [comment]
我也遇到了，期待修复～

**Comment by FlynnCao** [comment]
![image](https://github.com/mantou132/Spotify-Lyrics/assets/29702341/1bd9ce02-06b0-4f12-8945-6ab796053df3)

**Comment by zchen2001** [comment]
今天我加载的时候也出现了一样的bug 这个插件好好用 如果可以修复的话真的很感谢！

**Comment by mantou132** [comment]
上游项目似乎出问题了：https://neteasecloudmusicapi-docs.4everland.app/#/?id=%e6%90%9c%e7%b4%a2

例子：
https://music.xianqiao.wang/neteaseapiv2/search?keywords=%E6%B5%B7%E9%98%94%E5%A4%A9%E7%A9%BA

**Comment by oRevived** [comment]
@mantou132 I'm not sure if this is how this extension works, but if you add custom lyrics using the LRC editor the lyrics are saved on your google cloud functions server, right? I've added lyrics myself using the LRC editor, so it would be nice if it skips the netease API and used that one instead because it won't even let me use that. Thank you so much for your work. This extension is great :)

**Comment by mantou132** [comment]
<img width="1230" alt="Screenshot 2023-07-28 at 12 32 31" src="https://github.com/mantou132/Spotify-Lyrics/assets/3841872/58a1e6d8-eb80-4a2c-bd09-d7230841bc36">

update v1.5.31

If you enable this option, it will ignore NetEase Cloud Music API error and use Google Cloud Function API. The Google Cloud Function API consumes lyrics uploaded by users through this extended LRC editor.

如果你打开此选项将忽略 网易云音乐 API 使用 Google Cloud Function API。Google Cloud Function API 使用用户通过该扩展 LRC 编辑器上传的歌词。

**Comment by oRevived** [comment]
This issue seems to be fixed now. Netease API works fine

**Comment by flynncao** [comment]
> 暂时的解决方法：
> 
> 使用 Vercel 部署 [Binaryify/NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi) 登录自己的账号
> 
> https://github.com/mantou132/Spotify-Lyrics/blob/fe331f05c152f14d648a049b21a69aeb0abbbcf4/src/page/config.json#L2
> 
> 修改为自己的 api endpoint
> https://github.com/mantou132/Spotify-Lyrics/blob/fe331f05c152f14d648a049b21a69aeb0abbbcf4/src/page/config.ts#L25-L27
> 
> 去除 config.ts 中从 GitHub 获取配置的代码 重新打包即可

Thank you! It works for me.
