### ISSUE TITLE
chrome插件报错无法使用

### ISSUE THREAD

**Issue by edenxi** [mantou132/Spotify-Lyrics#108]
无法使用，报错如下，辛苦楼主看下谢谢

![image](https://github.com/mantou132/Spotify-Lyrics/assets/141910988/004633b9-981d-4593-a830-cac9536ccee2)
![image](https://github.com/mantou132/Spotify-Lyrics/assets/141910988/ce0b8738-9544-48ff-811c-d6475b29269d)

**Comment by mantou132** [comment]
具体是哪里无法使用。

是想自选歌词点击扩展按钮不出现歌词选择窗口吗？我也遇到了，但是过一会后也会打开，只是开启时间异常久
