### ISSUE TITLE
歌词显示位置设置为page时,点击歌词按钮没反应.

### ISSUE THREAD

**Issue by over-space** [mantou132/Spotify-Lyrics#109]
浏览器版本: Microsoft Edge 117.0.2045.35 (正式版本) (arm64)
插件版本: 1.5.31

**Comment by over-space** [comment]
从开始用该插件,歌词显示位置设置为page, 一直就没效果, 不知道歌词会显示在哪里

**Comment by mantou132** [comment]
是否有试过 PIP。

page 一般显示在左侧播放列表（没有更好的地方，有任何建议？）：
<img width="1231" alt="Screenshot 2023-11-29 at 22 00 03" src="https://github.com/mantou132/Spotify-Lyrics/assets/3841872/09b41999-8ea3-48d3-9556-69b7075201cc">

**Comment by efaun** [comment]
遇到了同样的问题, pip正常显示
![image](https://github.com/mantou132/Spotify-Lyrics/assets/13315821/b6549276-8b78-4423-8f6d-590aa25a4d7b)
切换到page点击无效, 控制台无报错
![NVIDIA_Share_aO722s78Mq](https://github.com/mantou132/Spotify-Lyrics/assets/13315821/055abb93-9623-4fa5-9bf1-598c5020e16c)

插件版本: 1.5.33
系统: Windows 11 22635.2915
浏览器: Google Chrome 122.0.6182.0

**Comment by mantou132** [comment]
很可能是语言环境的问题

我改成了[这个](https://github.com/mantou132/Spotify-Lyrics/blob/master/src/page/config.json#L4C33-L4C72)选择器。可以再试试

**Comment by efaun** [comment]
> 很可能是语言环境的问题，我这里英语界面一直没有问题，确实一直有收到找不到页面歌词容器的错误的错误。
> 
> 更新了，再试试

我这里没问题了, 谢谢
