### ISSUE TITLE
what i do after i download the zipped folder?

### ISSUE THREAD

**Issue by itsraghadalotibi** [mantou132/Spotify-Lyrics#112]
can you explain how can i use it please

**Comment by itsraghadalotibi** [comment]
chrom extension shows a massage "
Manifest file is missing or unreadable
Could not load manifest."

**Comment by oRevived** [comment]
Try following this tutorial: https://youtu.be/nBLt7JWSm7k

Make sure you've selected the right folder.

**Comment by DZROOK** [comment]
video is not available

**Comment by mantou132** [comment]
@DZROOK https://bashvlas.com/blog/install-chrome-extension-in-developer-mode
