### ISSUE TITLE
使用Spotify歌词时无法选择其他歌词

### ISSUE THREAD

**Issue by TkzcM** [mantou132/Spotify-Lyrics#125]
有一些歌曲的Spotify内置歌词时间轴错误，能否添加选择其他歌词的功能，感谢
例如：https://open.spotify.com/track/5nXyzQhRyDEVwygt1R6cMW
这首歌的网易云歌词时轴正确，Spotify内置歌词时轴对不上

**Comment by mantou132** [comment]
总结一下，需要添加一个选项，是否内置歌词优先，总步骤如下：

准备，并发访问 Firebase、网易：
1. 如果有自己上传歌词则使用自己上传的歌词
2. 如果有自己选择的网易歌词则使用该网易歌词

如果内置歌词优先：
1. 尝试加载内置歌词
2. 尝试自动从网易匹配歌词

否则：
1. 尝试自动从网易匹配歌词
2. 尝试加载内置歌词

**Comment by mantou132** [comment]
现在 Spotify 内置歌词似乎不能用了，暂时移除了。
