### ISSUE TITLE
really small lyrics page and no way to resize it (firefox)

### ISSUE THREAD

**Issue by samysogine** [mantou132/Spotify-Lyrics#127]
the page for the lyrics opens but stay at the bottom left and either can't be moved or be resized, even with a good eyesight i can't read that xD
what could cause that ?

**Comment by GSTDiandre** [comment]
If you're on Firefox, you should be able to pop the frame out the same way you would on any video frame and display it as picture-in-picture. Just hover over it and click the button that appears.

If not, you can resize the side panel which should make the lyrics appear bigger.

**Comment by samysogine** [comment]
Thank you mate, i still can't interact with it so i can't pop it out on PIP.
but the side panel works perfectly sorry i didn't thought of trying this, big thanks to you
