### ISSUE TITLE
Error/Bug.

### ISSUE THREAD

**Issue by Qwerty123455432112345** [mantou132/Spotify-Lyrics#128]
Recently (Over the past 2-3 days.), the lyrics for many songs have stopped displaying, and if they do display, They are often unsynchronized. Is this just my issue, or is it widespread?

**Comment by mantou132** [comment]
try v1.6.4

**Comment by Qwerty123455432112345** [comment]
> попробуй v1.6.4

And how to do it?

**Comment by Qwerty123455432112345** [comment]
I tried the browser extension, this error still persists.

> try v1.6.4

**Comment by salehrayan** [comment]
same. it was good before now most songs show "no lyrics" even if the correct song is selected manually

**Comment by oRevived** [comment]
> same. it was good before, now most songs show "no lyrics" even if the correct song is selected manually

Everything works fine for me. Could you give me a link to a song that says "no lyrics"? Just curious to see if I can replicate this.

**Comment by salehrayan** [comment]
> Everything works fine for me. Could you give me a link to a song that says "no lyrics"? Just curious to see if I can replicate this.

just some recent ones:
bloodtale - satanic panic - iron throne (BloodBound)

every album only has a few songs where the lyrics show up others are just "no lyrics"

**Comment by oRevived** [comment]
They also say "No lyrics" for me. Luckily, you can easily get synced lyrics by going to https://lrclib.net/ and copying the synced lyrics and pasting them into the Lyrics Editor (middle click on lyrics button) and clicking "Save" to upload them. I know this solution isn't ideal but I can't find these lyrics in the NetEase Cloud Music API which makes me think that they haven't been uploaded there yet or have been removed for whatever reason. Let me know if you have any further questions. :) 
![image](https://github.com/mantou132/Spotify-Lyrics/assets/79635740/8cd0fa99-efd6-48a7-a014-aa137baab519)
(I've uploaded lyrics for this song but it may not show up immediately for you so I'd suggest uploading them again if it still says "No lyrics")

**Comment by deeova** [comment]
how to open lyrics editor? where middle click on lyrics button? u mean on picture on picture?

**Comment by salehrayan** [comment]
middle click on the microphone icon

**Comment by mantou132** [comment]
Maybe a option should be provided to allow LRClib.net to replace the Netease API

**Comment by mantou132** [comment]
try v1.6.7 LRCLIB server


![Screenshot 2024-07-28 at 21 52 42](https://github.com/user-attachments/assets/f5a0b2f6-0260-4735-b719-d827e8fed61a)
