### ISSUE TITLE
Memory leak issue in GPU process

### ISSUE THREAD

**Issue by BehzadA** [mantou132/Spotify-Lyrics#13]
Memory leak issue in GPU process on MS Edge 80.0.361.62
How to produce problem:
1-Open Spotify PIP window
2-Open NewTab

**Comment by mantou132** [comment]
My machine:
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Google Chrome 82.0.4074.0 (Official Build) canary (64-bit)(Edge is based on Chromium)

<img width="1004" alt="Screen Shot 2020-03-02 at 10 52 12 AM" src="https://user-images.githubusercontent.com/3841872/75642525-c937e000-5c76-11ea-86ed-b4afade5d5f3.png">

This is normal, the lyrics in the pip window are synthesized as a video.

Don't know what your measurement is, and to what extent is the memory leaking?

**Comment by mantou132** [comment]
If there is a problem, please open issue it again
