### ISSUE TITLE
希望能自行修改搜索歌词请求的歌曲名和歌手

### ISSUE THREAD

**Issue by TkzcM** [mantou132/Spotify-Lyrics#130]
部分歌曲的标题在Spotify为日文，网易云为英文，导致无法获取到有效歌词
如 https://open.spotify.com/track/79W2OEftnPmH6Yvzg2H4eo 网易云 https://music.163.com/song?id=2093903080

**Comment by mantou132** [comment]
如果是歌手名字，可以在这里加上。

如果还搜不到的话可以在 popup 中按 `shift + i` 手动输入 网易云 id 。

**Comment by TkzcM** [comment]
感谢，没发现这个功能
不知道为啥mac上是Command + i
