### ISSUE TITLE
wrong lyrics/missing lyrics.

### ISSUE THREAD

**Issue by glitterbonez** [mantou132/Spotify-Lyrics#131]
A common issue is that many songs don't have lyrics. Some songs have the wrong lyrics. Some I have noticed: You just haven't earned it yet, baby! by The Smiths has the lyrics for The Boy with the Thorn in His Side by The Smiths and Oscillate Wildly by The Smiths has the lyrics for Rubber Ring by The Smiths.

Amazing extension!

**Comment by oRevived** [comment]
See my response in #128. Copy the lyrics from https://lrclib.net/ and paste them into the Lyrics Editor. :)
