### ISSUE TITLE
Small page view window

### ISSUE THREAD

**Issue by jhedgee** [mantou132/Spotify-Lyrics#137]
When displaying lyrics on open.spotify.com page view, not PiP, the lyrics screen is really small and tucked away in the bottom left corner. There should be an option to enlarge it or have it elsewhere.
![smallpageview](https://github.com/user-attachments/assets/ad59c118-a12d-488b-a9b0-d525fa09de23)

**Comment by oRevived** [comment]
https://github.com/user-attachments/assets/11205694-03ae-4172-a027-bf50f8c97cac

You can resize it :)

**Comment by jhedgee** [comment]
Thank you! I was overthinking it lol
