### ISSUE TITLE
unrecognized manifest key

### ISSUE THREAD

**Issue by RizzlerCope** [mantou132/Spotify-Lyrics#139]
"$schema" and the broswer_specific_settings is unrecognized manifest key any reason why?

**Comment by RizzlerCope** [comment]
it would show no lyrics

**Comment by oRevived** [comment]
> "$schema" and the broswer_specific_settings is unrecognized manifest key any reason why?

This is normal, so don't worry about it.

> it would show no lyrics

Which song does this happen to? You can try to use the extension pop up to try different lyrics, or if that still doesn't work try my solution in #128. Hope that works!

**Comment by RizzlerCope** [comment]
Any song I think bcos  of the manifest key is unrecognized

**Comment by oRevived** [comment]
I believe the API SpotifyLyrics uses (NeteaseCloudMusicApi) is down, which is why you aren't receiving lyrics. For the time being you can use my solution in #128.

**Comment by deeova** [comment]
can u help me where to middle click? on picture on picture?

**Comment by oRevived** [comment]
> can u help me where to middle click? on picture on picture?

Middle click on the lyrics button :)

**Comment by deeova** [comment]
I use YT music sir, do you have solution with YT music??

**Comment by oRevived** [comment]
It's the same procedure with YT Music. Middle click on the lyrics button next to the like button.

**Comment by mantou132** [comment]
dup https://github.com/mantou132/Spotify-Lyrics/issues/140

**Comment by deeova** [comment]
> It's the same procedure with YT Music. Copy the lyrics you got from [LRCLIB](https://lrclib.net/), middle click lyrics button, press CTRL + V to paste lyrics, and click on save.
> 
> ![image](https://private-user-images.githubusercontent.com/79635740/352553254-62857f85-2280-4dba-8758-e839e27cdbdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyMjQwMjIsIm5iZiI6MTcyMjIyMzcyMiwicGF0aCI6Ii83OTYzNTc0MC8zNTI1NTMyNTQtNjI4NTdmODUtMjI4MC00ZGJhLTg3NTgtZTgzOWUyN2NkYmRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDAzMjg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxODJmZDYxMWUyNWViOTk2NjI5NjU2YTk2NzNlZGUwODExNmE1MjI1YTNmMGUyMTE0ZjljNThmZTM5YjE3NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AQyngD_APJ1zxnSS8naplpA3ggM1lAqbz_swY6OMy70)
> 
> Hope this works!

Thanks dude for ur help, hope you have great day
