### ISSUE TITLE
又不显示歌词了

### ISSUE THREAD

**Issue by q769890208** [mantou132/Spotify-Lyrics#14]

**Comment by mantou132** [comment]
Spotify 更新了，css 需要更新。
另外 Chrome web store 不知是不是放假了，审核一直没过

**Comment by q769890208** [comment]
chrome商店找不到了，难道下架了吗？

**Comment by mantou132** [comment]
@q769890208 我上次想试下重新发布，结果下了之后发现不能发布了，审核状态不能动了。

**Comment by mantou132** [comment]
重新发布了。
v0.0.16
