### ISSUE TITLE
Unable to get lyrics 

### ISSUE THREAD

**Issue by oRevived** [mantou132/Spotify-Lyrics#140]
Netease API is unable to get lyrics (see below).
![Screenshot 2024-07-24 145115](https://github.com/user-attachments/assets/51bfc40c-3e4c-4a1c-a513-1fa712002ab4)

**Comment by yenting-biao** [comment]
I have the same issue. The popup of the extension menu also suggests that there are no available songs when playing.

**Comment by oRevived** [comment]
>It seems that some sort of verification is needed.

Funny enough a very similar thing happened this time last year, except it was even worse because you couldn't use the lyrics you uploaded! See #107.

If you really want lyrics you can always upload them via the lyrics editor. See [#139](https://github.com/mantou132/Spotify-Lyrics/issues/139#issuecomment-2250310678)

**Comment by mantou132** [comment]
The API seems to have returned to normal.

**Comment by mantou132** [comment]
v1.6.5

When Netease API is not available, use the LRCLIB API back
