### ISSUE TITLE
现在改的不会用了

### ISSUE THREAD

**Issue by q769890208** [mantou132/Spotify-Lyrics#21]
现在该怎么用，专辑页上不显示，点菜单栏的按钮auto select也没用

**Comment by mantou132** [comment]
还是自动显示在专辑封面上啊。

封面上不显示有两个原因：

1. Spotify 改版了，或者扩展不是最新版本
2. 没有找到合适的歌词

我测试了一下，没有问题，你检查下扩展版本，另外换首歌试试。

**Comment by mantou132** [comment]
那个 popup 是针对一些歌，网易上有歌词，但没有匹配上的情况用的。

比如中国歌手但是 Spotify 上是英文名，只要不知道怎么匹配，就可以在 popup 中自己选择歌曲，然后自动加载歌词。

**Comment by q769890208** [comment]
![image](https://user-images.githubusercontent.com/11898809/81505043-4f2f7180-931f-11ea-85ad-1fc452803376.png)
![image](https://user-images.githubusercontent.com/11898809/81505059-640c0500-931f-11ea-81c0-3ee35465da22.png)
你看一下，难道是我的版本不对？

**Comment by q769890208** [comment]
啊，我发现哪不对了，我傻了，不好意思 ，啊哈哈
