### ISSUE TITLE
Hi how to use

### ISSUE THREAD

**Issue by chenjuexu** [mantou132/Spotify-Lyrics#22]
I install it on add-on of Firefox,but it did not work.And I check your Github,does this software has to be installed by NodeJS?
A big tribute for this add-on,I really love it and wanna plug into that.
Thanks

**Comment by mantou132** [comment]
Click the button to the right of the "Like" button to display the lyrics.

https://addons.mozilla.org/en-US/firefox/addon/spotify-lyrics/

**Comment by chenjuexu** [comment]
Hi Mr. Mantou 
Thanks for your immediate reply,but I could not fiddle out where is the button in the right of "Like".Some issue came to MY spotify WEBPLAYER?

**Comment by mantou132** [comment]
![Screen Shot 2020-05-13 at 10 22 32 AM](https://user-images.githubusercontent.com/3841872/81764274-c7ef2300-9503-11ea-96b7-d6ba5ab70bc0.png)
