### ISSUE TITLE
Can't capture audio source when streaming from other devices

### ISSUE THREAD

**Issue by twxia** [mantou132/Spotify-Lyrics#23]
Hi there, this project is awesome. 👍 However, when streaming from other devices, there's no way to capture the audio source. The video tag is without the source link which is not streaming on the web. I think it's hard to fulfill this kind of feature perfectly. The progress bar on the web seems to use `setTimeout` stuff to render the progress which is not reliable.

**Comment by mantou132** [comment]
Yes, failure to calculate the delay will result in the inability to display real-time lyrics.
In addition, when I play on the phone, the webplayer does not even have a progress bar.
