### ISSUE TITLE
Enhancement regarding lyrics sourcing

### ISSUE THREAD

**Issue by derkanadier** [mantou132/Spotify-Lyrics#25]
Hey @mantou132 , loving this extension so I really appreciate your time spent developing it!

I noticed that many songs in my playlists are correctly identified by your extension but no lyrics are displayed (especially regarding less popular songs). However, I also noticed that most of these have lyrics available on www.genius.com
Hence, do you think it would be possible to integrate lyrics sourcing from that website? 

I'd be glad to be of any help if necessary :)

**Comment by mantou132** [comment]
Genius lyrics don’t seem to have a timestamp, so it ’s impossible to make synchronized lyrics.

Do you have a way to get time-stamped lyrics?

**Comment by derkanadier** [comment]
I see how that can be an issue. I'll look into that.

However, even if we have no timestamps from them, I thought it would still be useful for a user to see those lyrics instead of a blank album picture. In other words, having manually scrollable lyrics fetched from genius in case they aren't found from other sources with timestamps might be a nice feature to have.

**Comment by mantou132** [comment]
The lyrics are displayed in the pip window, and the pip window is actually the video being played, that is, the user cannot manually scroll the lyrics in this window.

Unless the lyrics are displayed elsewhere

**Comment by derkanadier** [comment]
Oh, alright. So if I understand correctly, the only content that can be displayed in a PIP window is a video?

**Comment by mantou132** [comment]
I find the only available is https://developer.musixmatch.com/documentation/api-reference/track-subtitle-get

but not for free

**Comment by derkanadier** [comment]
> I find the only available is https://developer.musixmatch.com/documentation/api-reference/track-subtitle-get
> 
> but not for free

Oh that's unfortunate :/

**Comment by DarthAV** [comment]
> I find the only available is https://developer.musixmatch.com/documentation/api-reference/track-subtitle-get
> 
> but not for free

Honestly not sure if this will work for a web extension, but spicetify is able to fetch Musixmatch lyrics for free for the desktop app by using free private tokens on a per-user basis.
You can take a look at the steps here: https://github.com/khanhas/genius-spicetify#musicxmatch

**Comment by mantou132** [comment]
V1.6.2 support spotify built-in lyrics, power by musixmatch

**Comment by oRevived** [comment]
Thoughts on adding [LRCLIB](https://github.com/tranxuanthang/lrclib) as an alternative lyrics provider? I've had a much higher success rate of getting lyrics from there instead of Netease's API. Not asking to get rid of Netease's API but having LRCLIB as an another option would be great as in my experience it has a much bigger library of lyrics than Netease and the quality is much better too. Perhaps the extension could check for lyrics from LRCLIB first, then NeteaseCloudMusicApi, and then Google Cloud Functions?
