### ISSUE TITLE
Remove lines that are unnecessary

### ISSUE THREAD

**Issue by ajiou** [mantou132/Spotify-Lyrics#27]
Some of the lines are useless, such as ads, asking for donate, and so on.

It might be possible to allow users to use regex to delete these lines.

**Comment by mantou132** [comment]
Options page added.

Now allow users to use clean mode, but just [don't show the lines without time stamp](https://github.com/mantou132/Spotify-Lyrics/commit/91552d11901a59767be28f359366854bd48afdbd#diff-7ac62f7e32b17e0a09ce82606b078f68R217)
