### ISSUE TITLE
Can't use media keys when PiP window is open

### ISSUE THREAD

**Issue by ujjwal123123** [mantou132/Spotify-Lyrics#29]
I don't know if it's bug or not but media keys don't work once PiP window is opened. Even after closing the window, the shortcuts do not work.

Spotify Lyrics 0.0.23
Ubuntu 20.04
Chrome 83.0.4103.61

**Comment by mantou132** [comment]
Thanks report.

On my computer, opening the pip window will cause the media key to not work, but closing the  window will allow the media key to resume working.

The extension does have bugs.

Based on how this extension works, i wrote simple demos:
- https://mantou132.github.io/javascript-learn/media-session/muted.html
- https://mantou132.github.io/javascript-learn/media-session/stream.html
They will cause the media key to not work.

It seems there is a problem with the browser, so I submit a bug:
- https://bugs.chromium.org/p/chromium/issues/detail?id=1092249
- https://bugzilla.mozilla.org/show_bug.cgi?id=1644034

This bug cannot be fixed yet

**Comment by mantou132** [comment]
Version 86.0.4210.0 (Official Build) canary (64-bit)
10.15.6 (19G73)

It seems that this problem cannot be reproduced anymore

However, cannot use the PiP window to control audio replay

**Comment by ujjwal123123** [comment]
Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)
Spotify Lyrics 1.2.7
Ubuntu 20.04

> It seems that this problem cannot be reproduced anymore
Unfortunately, the issue is still present on my machine. I do not know if it is because I am running an older version of Chrome.

> However, the pause button of the "Picture in Picture" window does not work
I can confirm this.

**Comment by mantou132** [comment]
Microsoft Edge (chromium 84) also has this problem.
But it has been fixed in Chrome 86.
