### ISSUE TITLE
This doesn't work with the new interface

### ISSUE THREAD

**Issue by muezis** [mantou132/Spotify-Lyrics#31]
Hi, I have Spotify with a new interface, and your extension doesn't work. The button in the player is just inactive, I click - and nothing happens. https://imgur.com/a/WVgHxPG Although the song is defined correctly in the extension menu. https://imgur.com/a/PL4M2ga

Not all users received the new interface. So if you need it, I can give you account with a new interface so you can fix it.

**Comment by mantou132** [comment]
Thanks for the report.

There is no reproduction on my machine, you can give an account that can be reproduced, and I can fix it immediately.

**Comment by muezis** [comment]
> Thanks for the report.
> 
> There is no reproduction on my machine, you can give an account that can be reproduced, and I can fix it immediately.

I sent it to 594mantou@gmail.com

**Comment by mantou132** [comment]
Logging into this account can't reproduce the bug.

I will update as soon as I find the reason

**Comment by mantou132** [comment]
Now that v0.0.25 has been released, you can check whether the problem has been fixed

**Comment by muezis** [comment]
> Now that v0.0.25 has been released, you can check whether the problem has been fixed

No, it still doesn't work, but I understand why - it's the browser. This is the first time I have come across the fact that Yandex Browser does not support the extension from the chrome store. So don't try to fix it.

**Comment by mantou132** [comment]
Note: Yandex Browser disable PiP by default, show lyrics like Firefox.
