### ISSUE TITLE
Control buttons in the "Picture in Picture" window do not work

### ISSUE THREAD

**Issue by mantou132** [mantou132/Spotify-Lyrics#36]
Related issue: #29 

https://bugs.chromium.org/p/chromium/issues/detail?id=1124695

**Comment by ashishbisoi236** [comment]
In my experience(Spotify only in web), while in PiP mode , pause button works and it pauses the music being played but after the pause, play button doesnt work  and I have to go back in the player to play it again.
All other buttons work except 'Play' one.

**Comment by sT00ne** [comment]
> In my experience(Spotify only in web), while in PiP mode , pause button works and it pauses the music being played but after the pause, play button doesnt work and I have to go back in the player to play it again.
> All other buttons work except 'Play' one.

I have the same problem with Youtube Music in web.

**Comment by mantou132** [comment]
fixed in chrome canary 92

**Comment by Troubleshooter5000** [comment]
Was this ever fixed in chrome production versions? It's still happening for me on Chrome 112.0.5615.50. The PIP buttons don't work, the same as described by [ashishbisoi236](https://github.com/ashishbisoi236).

**Comment by mantou132** [comment]
Can't reproduce on my chrome canary v114.0.5712.0
