### ISSUE TITLE
Where do I request or contribute for song lyrics?

### ISSUE THREAD

**Issue by njpromethium** [mantou132/Spotify-Lyrics#42]
I have a few in my playlist that I really want the lyrics of. I can contribute myself If I can.

**Comment by mantou132** [comment]
The lyrics are by default from https://music.163.com/, you can upload lyrics here

Addition, v1.4.0 Allow yourself to upload lyrics,

When "No lyrics" is displayed in the lyrics window, click the lyrics button with the middle mouse button to open the lyrics editing dialog:

<img width="1291" alt="Screen Shot 2020-08-11 at 9 40 29 AM" src="https://user-images.githubusercontent.com/3841872/89847478-b676ef00-dbb6-11ea-8397-d56783f0671b.png">

When the lyrics editing window opens, the song will start playing again. By default, the plain text of the lyrics has been loaded from genius. You only need to keep clicking "mark line" as the song plays to add a time stamp. Finally click "save" to save to the server.

By default, lyrics uploaded by other users will be loaded. You can turn off this option:

<img width="1256" alt="Screen Shot 2020-08-11 at 9 44 39 AM" src="https://user-images.githubusercontent.com/3841872/89847834-854aee80-dbb7-11ea-8cfe-236ce626948b.png">
