### ISSUE TITLE
"Failed to Fetch" on chromium edge

### ISSUE THREAD

**Issue by Xiaokang-Zhao1209** [mantou132/Spotify-Lyrics#49]
I just install it through chrome store. However with every song i played it just load for a long time and show"failed to fetch". Sometimes manually select the lyrics again works.

**Comment by mantou132** [comment]
Make sure your network can access Google Cloud functions:
https://us-central1-spotify-lyrics-ef482.cloudfunctions.net/getLyric

**Comment by Xiaokang-Zhao1209** [comment]
Solved! Thank you (i add the site to my proxy rules)
