### ISSUE TITLE
Enhancing GUI

### ISSUE THREAD

**Issue by MFRehan** [mantou132/Spotify-Lyrics#51]
Is it possible to just showing a small bar (like a status bar) with the lyrics instead of a square with the lyrics on it? 
It occupies a big area of the screen I know that I can resize it but even when resizing it the lyrics just become too small and there is a black margin at both edges that is wasteful. 
![Screenshot from 2020-08-29 01-43-23](https://user-images.githubusercontent.com/41120136/91622805-2ea42980-e999-11ea-8b17-4c5788eeeec3.png)

**Comment by mantou132** [comment]
This depends on the capabilities of chrome, currently it is not possible to display long windows

https://bugs.chromium.org/p/chromium/issues/detail?id=1123249

In addition, it is impossible to embed lyrics into the status bar, because the browser cannot have such a function.
