### ISSUE TITLE
option to disable or enable auto-scroll?

### ISSUE THREAD

**Issue by kirbyter** [mantou132/Spotify-Lyrics#52]
Hi @mantou132 , thank you for this extension! i really like the clean style you've designed.
just wondering if there could be an option to disable the auto-scroll/synchronisation so that a user can scroll through the lyrics manually? maybe not in PIP but as a floating panel or something? thanks!

**Comment by mantou132** [comment]
The feature of this extension is automatic scrolling. If you need to scroll the lyrics manually, you can try other extensions
