### ISSUE TITLE
Support Spotify's official lyric?

### ISSUE THREAD

**Issue by ccloli** [mantou132/Spotify-Lyrics#55]
I noticed that Spotify now has lyric feature on web player, is it possible to use the official lyric api first? Since some songs are not using the same name as in NetEase music (Japan especially, some of them are using Roman as song name instead of Japanese if you're not in Japan).

URL: https://open.spotify.com/lyrics
The URL will be available when playing song has lyric.

![Snipaste_2020-10-12_10-36-02.png](https://i.loli.net/2020/10/12/loEeN7MXPuwJiSc.png)

API: https://spclient.wg.spotify.com/lyrics/v1/track/5MTcqelobfRlBHUwICBmAm?market=from_token
You might need to pass `Authorization` header manually.

![Snipaste_2020-10-12_10-36-22.png](https://i.loli.net/2020/10/12/fCdzsrotYkRw3W2.png)

**Comment by VosMovok** [comment]
I hope this is implemented somtimes in the future. Sometimes there's no lyrics from the extension source meanwhile the official has one. Bit of a bummer if it can't just fetch lyrics from the official api as it's already available on the web player.

**Comment by yutotakano** [comment]
I hope this is also taken a look at, following the global rollout of Spotify official lyrics. Since Spotify-Lyrics is able to inject custom functionality into the web player, I'm assuming it shouldn't be so difficult to grab the Authorization header as well. The endpoint still works, and contains timed lyrics in JSON format.

**Comment by MisteryMonster** [comment]
Why not retain the official lyrics button? It just works. Add extra menu to do the lyrics search when there is no lyrics available. I think is difficult to determine when to use lyrics search automatically.

**Comment by SuperPat45** [comment]
Spotify official lyrics are now a premium feature...
Thankfully, this plugin is a good alternative.

**Comment by mantou132** [comment]
At present, the lyrics are only available in Premium users, but API is still available for the time being.

I consider implementing this function. I wonder if there is risk to user accounts? Maybe the Spotify lyrics are not enabled by default?

**Comment by mantou132** [comment]
This API does not appear to be available for newly released songs.
For Premium users, maybe using a different API would work on all songs?

<img width="588" alt="Screenshot 2024-05-19 at 13 11 34" src="https://github.com/mantou132/Spotify-Lyrics/assets/3841872/644a228a-1d23-4a89-9ec0-337d8d4b0450">

<img width="703" alt="Screenshot 2024-05-19 at 13 11 45" src="https://github.com/mantou132/Spotify-Lyrics/assets/3841872/dc61dec1-02e9-41e6-9c17-69558643d967">

**Comment by TkzcM** [comment]
new api endpoint
${spotifyAPI}/color-lyrics/v2/track/${trackId}?format=json&vocalRemoval=false&market=from_token
```javascript
const spLyrics = (await res2.json())["lyrics"];
if (spLyrics.syncType === "LINE_SYNCED") {
   return spLyrics.lines.map(
      ({ startTimeMs, words }) => ({
         startTime: startTimeMs / 1e3,
         text: words
      })
   ).flat();
}
```

**Comment by mantou132** [comment]
> new api endpoint ${spotifyAPI}/color-lyrics/v2/track/${trackId}?format=json&vocalRemoval=false&market=from_token
> 
> ```js
> const spLyrics = (await res2.json())["lyrics"];
> if (spLyrics.syncType === "LINE_SYNCED") {
>    return spLyrics.lines.map(
>       ({ startTimeMs, words }) => ({
>          startTime: startTimeMs / 1e3,
>          text: words
>       })
>    ).flat();
> }
> ```

404 Not Found, only Premium users?

**Comment by mantou132** [comment]
> new api endpoint ${spotifyAPI}/color-lyrics/v2/track/${trackId}?format=json&vocalRemoval=false&market=from_token
> 
> ```js
> const spLyrics = (await res2.json())["lyrics"];
> if (spLyrics.syncType === "LINE_SYNCED") {
>    return spLyrics.lines.map(
>       ({ startTimeMs, words }) => ({
>          startTime: startTimeMs / 1e3,
>          text: words
>       })
>    ).flat();
> }
> ```

API available, but I have never obtained synchronous lyrics

**Comment by TkzcM** [comment]
It may be related to the account region settings, my account is in Japan region, lyrics providerDisplayName is プチリリ.
![image](https://github.com/user-attachments/assets/e2bef1e2-ebcb-4eb7-a5be-f83a28e51fee)
