### ISSUE TITLE
请求帮助：右键找不到扩展内置的LRC 编辑器，只能看见自定义歌词的显示

### ISSUE THREAD

**Issue by Birdling** [mantou132/Spotify-Lyrics#56]
![image](https://user-images.githubusercontent.com/62651551/96359353-89116900-1144-11eb-8313-152dff97166d.png)

**Comment by mantou132** [comment]
中键打开歌词编辑器

最好等歌词加载好了再打开

**Comment by Birdling** [comment]
> 中键打开歌词编辑器
> 
> 最好等歌词加载好了再打开

感谢！
