### ISSUE TITLE
为什么挂着vpn就能自动匹配歌词，而且还能找到一些国内没有的歌词

### ISSUE THREAD

**Issue by q769890208** [mantou132/Spotify-Lyrics#61]
为什么挂着vpn就能自动匹配歌词，而且还能找到一些国内没有的歌词

**Comment by mantou132** [comment]
用户手动匹配的数据保存在 Google firebase。

首先会从 Google firebase 查询，所以必须能访问 Google 的 firebase 才能正常使用扩展。

用户也可以上传歌词。
