### ISSUE TITLE
Suggestion: Remember placement on screen

### ISSUE THREAD

**Issue by emmyapi** [mantou132/Spotify-Lyrics#62]
I like it placed as a replacement for the album cover art (if extended) in the bottom left corner. Maybe it is possible to get it to remember the placement for any location, or maybe this fixed location could be an option in the future. 
I absolutely love you guys and your work. 
Thank you.

**Comment by mantou132** [comment]
<img width="563" alt="Screen Shot 2021-01-05 at 2 15 49 AM" src="https://user-images.githubusercontent.com/3841872/103565846-035bb900-4efc-11eb-8c14-036ef1bf6d2f.png">
Have you tried this option?

**Comment by emmyapi** [comment]
> <img alt="Screen Shot 2021-01-05 at 2 15 49 AM" width="563" src="https://user-images.githubusercontent.com/3841872/103565846-035bb900-4efc-11eb-8c14-036ef1bf6d2f.png">
> 
> Have you tried this option?

Oh haha. Thank you. This is perfect for me 👍
