### ISSUE TITLE
How to open LRC editor?

### ISSUE THREAD

**Issue by lutunaa** [mantou132/Spotify-Lyrics#63]
you say "click the lyrics button with the middle mouse button to open the lyrics editing". where is the lyrics button?

**Comment by lutunaa** [comment]
you say "click the lyrics button with the middle mouse button to open the lyrics editing". where is the lyrics button?

**Comment by mantou132** [comment]
If the extension is working properly, the lyrics button is displayed in the lower left corner
![image](https://user-images.githubusercontent.com/3841872/103949934-fd254100-5176-11eb-870c-249973cb68df.png)
