### ISSUE TITLE
How to use another source to find french rap lyrics ?

### ISSUE THREAD

**Issue by sanjuant** [mantou132/Spotify-Lyrics#66]
Hello,

I noticed that unfortunately the bank of lyrics for French rap was rather weak.

Is it possible to include another source to have more lyrics available?

Currently via the Deezer API it is possible to retrieve a lot of lyrics. To do this you first need to retrieve the song id [https://api.deezer.com/search?q=sch,marche%20noir](https://api.deezer.com/search?q=sch,marche%20noir) .

Then you have to call the API with this id.

[https://www.deezer.com/ajax/gw-light.php?method=song.getLyrics&api_version=1.0&api_token=[api-token]&sng_id=[song-id]](https://www.deezer.com/ajax/gw-light.php?method=song.getLyrics&api_version=1.0&api_token=[api-token]&sng_id=[song-id])

Source: [https://stackoverflow.com/questions/42165724/how-to-get-lyrics-from-the-deezer-api#answer-59822502](https://stackoverflow.com/questions/42165724/how-to-get-lyrics-from-the-deezer-api#answer-59822502)

I would be happy to contribute if you put me on the track to add sources ;).

**Comment by mantou132** [comment]
dup #25
