### ISSUE TITLE
Is the project dead? 

### ISSUE THREAD

**Issue by sowhereisit** [mantou132/Spotify-Lyrics#67]
Seeing this has been removed from Chrome Store. 
Just started to use it. This is perfect until now...
Please dont go :(

**Comment by mantou132** [comment]
由于版权原因被下架了。

要用的话可以在 release 页面下载 zip。 自行在浏览器中加载扩展。

抱歉。

===

It was removed from the chrome webstore due to copyright reasons.

If you want to use it, you can download the zip from the release page. Load the extension in the browser yourself.

Sorry.

It's not dead yet
