### ISSUE TITLE
Your Extension no longer can be found on Chrome Store. Pls Come back I really like your

### ISSUE THREAD

**Issue by PhiNhat2211** [mantou132/Spotify-Lyrics#68]

**Comment by PhiNhat2211** [comment]
I just wanna say thanks for creating a great extension. Honestly, If your extension doesn't exist anymore, I will be very dissapointed.

**Comment by monywoex** [comment]
是的,在chrome商店没有办法下载到了,我也不知道是什么原因.
但是利可以下载源代码,然后用浏览器的开发者模式,本地加载插件

**Comment by alecthekulak** [comment]
Bump, issue still exists (think it was removed even from my browser where it was already installed somehow). Can anyone provide instructions for the temporary solution proposed by monywoex?

**Comment by PhiNhat2211** [comment]
> 是的,在chrome商店没有办法下载到了,我也不知道是什么原因.
> 但是你可以下载源代码,然后用浏览器的开发者模式,本地加载插件

You still can download latest version of this extension 
Step 1: Download it through 'https://github.com/mantou132/Spotify-Lyrics/releases/tag/1.5.20' and unzip it
Step 2:Turn on your Developer mode of Chrome/Egde
Step 3: In Extension tab of Chome/Edge Choose 'Load Unpacked' and Select unzip folder of extension

**Comment by mantou132** [comment]
由于版权原因被下架了。

要用的话可以在 [release](https://github.com/mantou132/Spotify-Lyrics/releases) 页面下载 zip。 自行在浏览器中加载扩展。

抱歉。

=== 

It was removed from the chrome webstore due to copyright reasons.

If you want to use it, you can download the zip from the [release](https://github.com/mantou132/Spotify-Lyrics/releases) page. Load the extension in the browser yourself.

Sorry.

**Comment by PhiNhat2211** [comment]
> 由于版权原因被下架了。
> 
> 要用的话可以在 [release](https://github.com/mantou132/Spotify-Lyrics/releases) 页面下载 zip。 自行在浏览器中加载扩展。
> 
> 抱歉。
> 
> ===
> 
> It was removed from the chrome webstore due to copyright reasons.
> 
> If you want to use it, you can download the zip from the [release](https://github.com/mantou132/Spotify-Lyrics/releases) page. Load the extension in the browser yourself.
> 
> Sorry.

Sorry to hear that. Goodluck dude
