### ISSUE TITLE
自動 Fallback 到搜尋結果的第一個項目

### ISSUE THREAD

**Issue by hugwalk** [mantou132/Spotify-Lyrics#69]
大部分 YouTube Music 上的歌曲都會預設顯示成「沒有歌詞」，但打開搜尋結果卻顯示好幾個。

是否可以提供「找不到歌詞時自動 Fallback 到搜尋結果中的第一項」的功能開關？可以大量省去手動選擇歌詞的時間。

**Comment by mantou132** [comment]
自动选择歌词是这个扩展的基本功能。

你说的这种情况只是说明候选列表中没有符合要求的，YouTube music 出现的话很可能是时长不同的原因。

目前 Spotify web player 是支持的最好的。
