### ISSUE TITLE
Cannot find the extension on Firefox. 

### ISSUE THREAD

**Issue by RRMaximiliano** [mantou132/Spotify-Lyrics#71]
Is the extension not longer to be in development for firefox?

**Comment by mantou132** [comment]
1. Download zip file. https://github.com/mantou132/Spotify-Lyrics/releases
2. Goto about:config, toggle "xpinstall.signatures.required". [detail](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users)
3. Goto about:addons, click menu "Install Add-on From File"
