### ISSUE TITLE
Netease blocks requests now?

### ISSUE THREAD

**Issue by LordXerus** [mantou132/Spotify-Lyrics#74]
I can't fetch lyrics anymore. It has been giving `Error: Failed to fetch`. It has been working a few hours ago.

It seems that Netease is blocking lyrics request from the extension.

![image](https://user-images.githubusercontent.com/34696211/123142879-28df6f00-d417-11eb-92dd-b3bb71a5e4ac.png)

**Comment by mantou132** [comment]
There are a lot of unknown requests recently, causing server downtime.

For this, I changed an endpoint.
