### ISSUE TITLE
Can't install in Firefox latest version

### ISSUE THREAD

**Issue by hosein2398** [mantou132/Spotify-Lyrics#75]
Hey, 
I'm using Firefox 89 and I can't install the extension, I get:
```
Can't install this extension because it's not verfied
```

More info from Firefox:
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

**Comment by mantou132** [comment]
You can go to `about:config`, search `xpinstall.signatures.required`, double-click close verification

**Comment by hosein2398** [comment]
Still getting same error with this.

**Comment by mantou132** [comment]
@hosein2398 Did you download the zip file?
https://github.com/mantou132/Spotify-Lyrics/releases

Here is my screen recording (low resolution): https://www.youtube.com/watch?v=FwDLXPeSpDQ

**Comment by hosein2398** [comment]
This is because you are using Firefox Nightly.
and as written here 
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox#w_what-are-my-options-if-i-want-to-use-an-unsigned-add-on-advanced-users
there seems to be no way for normal ff to change it.

**Comment by mantou132** [comment]
you can now download self-hosting .xpi file in the [Release](https://github.com/mantou132/Spotify-Lyrics/releases) page.
