### ISSUE TITLE
How to use this extension in YouTube Music app?

### ISSUE THREAD

**Issue by pmpmpro** [mantou132/Spotify-Lyrics#77]
This extension works perfectly fine in Spotify PWA. But I am not able to find a way of adding this extension to the youtube music PWA and the [YouTube Music desktop app by th-ch](https://github.com/th-ch/youtube-music)

**Comment by mantou132** [comment]
I just updated it.

Only supports YouTube Music PWA(or webpage), not any other YouTube Music clients
