### ISSUE TITLE
已在开发者模式中加载了解压文件夹，还是显示错误

### ISSUE THREAD

**Issue by lawinvera** [mantou132/Spotify-Lyrics#78]
抱歉打扰了，加载该拓展时还是未能成功，错误详情详见附图：
![image](https://user-images.githubusercontent.com/87893731/126862001-d78a8581-087d-4426-b243-71ce084b3554.png)

![image](https://user-images.githubusercontent.com/87893731/126861949-5e06d011-01fe-40a8-ae23-c3ef74aa0ebf.png)
不知图片是否可见，以下为错误提示内容：
Unrecognized manifest key 'browser_specific_settings'.
 "browser_specific_settings": {
    "gecko": {
      "id": "{d5bcc68d-856a-41e2-8021-d4c51f3b8e4a}",
      "strict_min_version": "78.0"
    }
  },

**Comment by Captain6Price** [comment]
一样的问题
Same problem
蹲一个解决办法
waiting for a solution

**Comment by mantou132** [comment]
这只是个警告。是 Firefox 扩展的格式。
不妨碍 Chrome 继续使用。

近几天 Spotify 更新了，歌词按钮没有先，如果你是因为没看到歌词按钮了误以为是这个的问题的话更新到 v1.5.23 就好了。

**Comment by Captain6Price** [comment]
> 这只是个警告。是 Firefox 扩展的格式。
> 不妨碍 Chrome 继续使用。
> 
> 近几天 Spotify 更新了，歌词按钮没有显示，如果你是因为没看到歌词按钮误以为是这个的问题的话更新到 v1.5.23 就好了。

非常感谢这么及时的更新，已能正常使用，长久以来一直运行的很稳定也很好用，nice job，借这个渠道对作者表达一下敬意和感谢吧

**Comment by lawinvera** [comment]
> 这只是个警告。是 Firefox 扩展的格式。
> 不妨碍 Chrome 继续使用。
> 
> 近几天 Spotify 更新了，歌词按钮没有显示，如果你是因为没看到歌词按钮误以为是这个的问题的话更新到 v1.5.23 就好了。

是的，今天再打开后发现有like可以点，就出现了。非常谢谢~~请问这个可以将网易云作为歌词库吗？
