### ISSUE TITLE
About the version （maybe）

### ISSUE THREAD

**Issue by bohemian-lh** [mantou132/Spotify-Lyrics#79]

**Comment by bohemian-lh** [comment]
Unrecognized manifest key 'browser_specific_settings'


 "browser_specific_settings": {
    "gecko": {
      "id": "{d5bcc68d-856a-41e2-8021-d4c51f3b8e4a}",
      "strict_min_version": "78.0"
    }
  },

**Comment by mantou132** [comment]
这是一个兼容 Firefox 的字段，chrome 虽然不能识别，但也能正常工作。
