### ISSUE TITLE
Just a question about the censoring...

### ISSUE THREAD

**Issue by stellqrr** [mantou132/Spotify-Lyrics#80]
Can I make it not censor the F word if you will?

**Comment by LordXerus** [comment]
I'm pretty sure that is controlled by the service where this extension pulls its lyrics from, not this extension.

**Comment by mantou132** [comment]
I have made this effort.
Download genius lyrics, replace the source lyrics.

https://github.com/mantou132/Spotify-Lyrics/blob/master/src/page/genius.ts

**Comment by stellqrr** [comment]
> I have made this effort.
> Download genius lyrics, replace the source lyrics.
> 
> https://github.com/mantou132/Spotify-Lyrics/blob/master/src/page/genius.ts

Thank you so much.
