### ISSUE TITLE
Larger window size and font

### ISSUE THREAD

**Issue by spotifyuser01** [mantou132/Spotify-Lyrics#81]
Hi this looks fantastic, but my eyesight isnt so great and need to be able to have larger font with a much bigger popup window... where can i adjust the size of the window please?
Many thanks in advance

**Comment by mantou132** [comment]
v1.5.25 allow you `ctrl/command + =/-` adjust window size.

**Comment by spotifyuser01** [comment]
sorry for the confusion, but i mean the pip window (picture in picture) how is it referenced by your script? and then how can the script be adjusted to the pip larger?
many thanks for your help

**Comment by mantou132** [comment]
The pip window size cannot be adjusted by script, you can drag it in the corner to adjust the size.
