### ISSUE TITLE
希望能提供不转换简繁汉字的选项

### ISSUE THREAD

**Issue by TkzcM** [mantou132/Spotify-Lyrics#86]
部分日语歌词无论选择简体或繁体，转换后与原文均有不同

如：
打开“繁体中文歌词”开关： 触れて → 觸れて
关闭开关：僕は → 仆は

**Comment by ccloli** [comment]
api 返回的确实是原始文本，从代码上看，应该是在对文本格式化时，直接把文本强制转换成了简体中文

https://github.com/mantou132/Spotify-Lyrics/blob/c596319ee7911613de4e8c8842e2aab0ebd682bf/src/page/lyrics.ts#L1
https://github.com/mantou132/Spotify-Lyrics/blob/c596319ee7911613de4e8c8842e2aab0ebd682bf/src/page/lyrics.ts#L84-L86

**Comment by TkzcM** [comment]
是的，目前我Fork去掉sify先用着了

**Comment by mantou132** [comment]
@TkzcM 

歌手、歌曲名称简化是方便搜索。

歌词会先简化，目的是让“繁体歌词”这个起作用，这确实会对日文歌词有影响。

**Comment by mantou132** [comment]
1.6.3 默认不转换了。
