### ISSUE TITLE
出现这个是什么问题

### ISSUE THREAD

**Issue by yueoooooooooooo** [mantou132/Spotify-Lyrics#90]
![image](https://user-images.githubusercontent.com/98028545/150129929-2b5e6227-7f18-4792-9e00-dbd866063e3a.png)

**Comment by yueoooooooooooo** [comment]
1.5.26Spotify出不来歌词按钮

**Comment by mantou132** [comment]
那个⚠️没有关系。

<img width="130" alt="Screen Shot 2022-01-21 at 5 53 30 PM" src="https://user-images.githubusercontent.com/3841872/150506004-49378243-679f-49ab-ab72-bfb0c11be253.png">
图标改了，也没有🎤吗？

**Comment by yueoooooooooooo** [comment]
已解决 多谢👍
