### ISSUE TITLE
No longer working on YouTube Music?

### ISSUE THREAD

**Issue by oRevived** [mantou132/Spotify-Lyrics#98]
Noticed this yesterday but lyrics are no longer working in YouTube Music (although they seem to work fine on Spotify). Lyrics button is not showing and pressing L does not work either. 
![bug](https://user-images.githubusercontent.com/79635740/193124358-d30bd18e-32e9-4835-8035-aad15eb45baf.png)
Tried installing it on the Edge Add-ons store with no luck and refreshing does not seem to fix the issue either.
Also tried on Chrome and Firefox with the same result.

Thanks

**Comment by mantou132** [comment]
![image](https://user-images.githubusercontent.com/3841872/193459131-6ef96561-28dc-400d-89ab-42a9787c3955.png)
